FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

RUN apt-get update

RUN apt-get install sqlite3 -y

COPY ./Database/EventDatabase.db /app/Database/EventDatabase.db

COPY --from=build /app/out .

EXPOSE 80

ENTRYPOINT [ "dotnet", "EventSignupApi.dll" ]